"""empty message

Revision ID: 78d9dce00007
Revises: 9a17287ebd83
Create Date: 2020-10-10 18:01:38.113640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d9dce00007'
down_revision = '9a17287ebd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('root_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'root_id')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
